apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flaskapp
  description: Flask app that displays the time.
  annotations:
    github.com/project-slug: maker2413/flaskapp
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
